---
title: "M280 Assignment2"
author: "Shuang Gao"
date: "2018/2/12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## Read Chapter 7 (Exploratory Data Analysis) of R for Data Science and do exercises 7.3.4, 7.4.1, 7.5.1.1, 7.5.2.1, and 7.5.3.1.

### 7.3.4
1. Explore the distribution of each of the x, y, and z variables in diamonds. What do you learn? Think about a diamond and how you might decide which dimension is the length, width, and depth.
```{r}
library(tidyverse)
ggplot(data = diamonds) +
  geom_histogram(mapping = aes(x = x), binwidth = 0.5) +
  scale_x_continuous(breaks = seq(0, 12, by = 0.5 )) +
  scale_y_continuous(breaks = seq(0, 14000, by = 2000)) +
  coord_cartesian(x = c(0, 12)) +
  coord_cartesian(y = c(0, 14000)) +
  labs(
    title = "histgram for x variable in diamonds",
    x = "x (mm)",
    y = "count of diamonds"
  )

ggplot(data = diamonds) +
  geom_histogram(mapping = aes(x = y), binwidth = 0.5) +
  scale_x_continuous(breaks = seq(0, 60, by = 5)) +
  scale_y_continuous(breaks = seq(0, 14000, by = 2000)) +
  coord_cartesian(x = c(0,60)) +
  coord_cartesian(y = c(0,14000)) +
  labs(
    title = "histgram for y varibale in diamonds",
    x = "y (mm)",
    y = "count of diamonds"
  )
  
ggplot(data = diamonds) +
  geom_histogram(mapping = aes(x = z), binwidth = 0.5) +
  scale_x_continuous(breaks = seq(0, 35, by = 5)) +
  scale_y_continuous(breaks = seq(0, 14000, by = 2000)) +
  coord_cartesian(xlim = c(0,35), ylim = c(0,14000)) +
  labs(
    title = "histgram for z varibale in diamonds",
    x = "z (mm)",
    y = "count of diamonds"
  )
```
* For variable x in diamond, most of the x values are located from 3.75 to 9.25 mm.

